# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Creative Economy Pilot Project
author: City of Sacramento
email: support@innovatesac.org
description: >- # this means to ignore newlines until "baseurl:"
  The Creative Economy Pilot Project is an initiative by the City of Sacramento to increase economic activity and improve public spaces through art, food, and technology initiatives. The City is offering $500,000 in microgrants up to $5,000 and larger grants up to $25,000 to support projects such as pop-up events, art installations, and street performances in Sacramento’s neighborhoods.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: innovatesac
github_username:  innovatesac

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Stylesheets
sass:
    sass_dir: _sass
    style: compressed

# Specify collection of projects
collections:
  projects:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
